services:
  - type: web
    name: drf-blog
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_project.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"   # After first deploy, set to your Render domain
      - key: DATABASE_URL
        fromDatabase:
          name: drf-blog-db
          property: connectionString
    autoDeploy: true

databases:
  - name: drf-blog-db
    plan: free
